### ISSUE TITLE
Launch Planning for Tuesday

### ISSUE THREAD

**Issue by Ly0n** [protontypes/climate-triage#24]
Here a list of things we need to do for the hard launch of this project Tuesday:

**Launch start: 11:00 CET**

## ToDOs: 
- [ ] Create oneliner for HN. ( 80 characters max ) 
	- [ ]  Find your open source contribution to climate change.
	- [ ]  Find the Open Source you need to help fight climate change.
	- [ ]  Contribute to open source focused on climate technology and sustainability.
- [ ] Create social media image. The current AI generator image do not look really professional.
- [ ] Create social media post for:
    - [x] Reddit
    - [x] LinkedIn
    - [ ] Slack 
    - [x] SustainOSS
    - [x] Twitter 
    - [x] Product Hunt
- [x] Create Blog post for OpenSustain.tech and LF Energy. 
	- [x]  https://docs.google.com/document/d/1JS0afkg0cGD5KNWO84uGw6oXV6Lrs33ZsXaJbLiEpTM/edit
- [x] Add Launch message to ClimateTriage header
- [x] Add Launch message to OpenSustain.tech header
- [ ] Contact influencer in climate and sustainability if they want to share the website.

**Comment by andrew** [comment]
I think this can be closed now that it's launched?
